// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsr8rwTSM4plLTp55XKw8nYyAKwUuKyfo',
    appId: '1:1063351266211:web:f00ba12003095ac5e4c816',
    messagingSenderId: '1063351266211',
    projectId: 'to-do-list-426e1',
    authDomain: 'to-do-list-426e1.firebaseapp.com',
    storageBucket: 'to-do-list-426e1.appspot.com',
    measurementId: 'G-TXEX2PKC6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIpSY03EdolX2Y_K1S9bUjjbJubWoVp2E',
    appId: '1:1063351266211:android:8edd680653cba612e4c816',
    messagingSenderId: '1063351266211',
    projectId: 'to-do-list-426e1',
    storageBucket: 'to-do-list-426e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACp4JSHu-NZ0ExJ6WinHr_rPR0QSe0zGQ',
    appId: '1:1063351266211:ios:9624eb6f607c7817e4c816',
    messagingSenderId: '1063351266211',
    projectId: 'to-do-list-426e1',
    storageBucket: 'to-do-list-426e1.appspot.com',
    iosBundleId: 'com.example.untitled8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACp4JSHu-NZ0ExJ6WinHr_rPR0QSe0zGQ',
    appId: '1:1063351266211:ios:3fd601e1bab318c2e4c816',
    messagingSenderId: '1063351266211',
    projectId: 'to-do-list-426e1',
    storageBucket: 'to-do-list-426e1.appspot.com',
    iosBundleId: 'com.example.untitled8.RunnerTests',
  );
}
